name: Build

on:
  schedule:
    - cron: 0 0 */7 * *

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Log into registry
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Build and push image
        uses: docker/build-push-action@v2
        with:
          push: true
          platforms: linux/amd64,linux/386
          tags: ghcr.io/catthehacker/hastebin-docker:latest      
